name = "aiw211"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "c7afecb1-2dd0-47a4-a17c-7468ce8615cf"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
